"""Fixed problem related to the last db upgrade

Revision ID: 60439358f0c7
Revises: 29aa1297544a
Create Date: 2023-05-08 17:30:24.404975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60439358f0c7'
down_revision = '29aa1297544a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corsi', schema=None) as batch_op:
        batch_op.alter_column('codice',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=5),
               existing_nullable=False)
        batch_op.alter_column('codice_insegnamento',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=4),
               existing_nullable=True)

    with op.batch_alter_table('esami', schema=None) as batch_op:
        batch_op.alter_column('codice_corso',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=5),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('esami', schema=None) as batch_op:
        batch_op.alter_column('codice_corso',
               existing_type=sa.String(length=5),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('corsi', schema=None) as batch_op:
        batch_op.alter_column('codice_insegnamento',
               existing_type=sa.String(length=4),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('codice',
               existing_type=sa.String(length=5),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
